name: KMP Multiplatform CI

on: [push]

jobs:
  run-all-tests:
    # Запускаем сборку на быстром Linux-сервере
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Запускаем универсальную команду, которую предложил сам Gradle!
      # Она проверит наш общий тест в commonTest для всех платформ сразу
      - name: Run All KMP Tests
        run: ./gradlew :composeApp:test
